name: Build Tweak
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build
        run: |
          # 1. ติดตั้ง Theos แบบรวดเร็ว
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          
          # 2. สั่ง Build โดยใช้ SDK ในเครื่อง (แก้ปัญหา Module Error)
          make clean && make FINALPACKAGE=1 SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version)
        env:
          SYSROOT: $(xcrun --sdk iphoneos --show-sdk-path)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Files
          path: |
            .theos/obj/arm64/*.dylib
            packages/*.deb
