name: Build Tweak
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup and Build
        run: |
          git clone --depth 1 --recursive https://github.com/theos/theos.git ~/theos
          export THEOS=~/theos
          export PATH="$THEOS/bin:$PATH"
          
          # เพิ่ม Flag พิเศษเพื่อข้าม Error ในโค้ด C++ (Esp.h)
          make clean && make FINALPACKAGE=1 \
            SDKVERSION=$(xcrun --sdk iphoneos --show-sdk-version) \
            ADDITIONAL_CFLAGS="-fpermissive" \
            ADDITIONAL_OBJCCFLAGS="-fpermissive"
        env:
          SYSROOT: $(xcrun --sdk iphoneos --show-sdk-path)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Tweak-Files
          path: |
            .theos/obj/arm64/*.dylib
            packages/*.deb
